# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/estadistica',
                'doc_host': 'https://Itzelep.github.io',
                'git_url': 'https://github.com/Itzelep/estadistica',
                'lib_path': 'estadistica'},
  'syms': {'estadistica.core': {'estadistica.core.foo': ('core.html#foo', 'estadistica/core.py')}}}
