# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/estadistica',
                'doc_host': 'https://Itzelep.github.io',
                'git_url': 'https://github.com/Itzelep/estadistica',
                'lib_path': 'estadistica'},
  'syms': { 'estadistica.core': { 'estadistica.core.calcular_desviacion_estandar': ( 'statistics.html#calcular_desviacion_estandar',
                                                                                     'estadistica/core.py'),
                                  'estadistica.core.calcular_media': ('statistics.html#calcular_media', 'estadistica/core.py'),
                                  'estadistica.core.calcular_mediana': ('statistics.html#calcular_mediana', 'estadistica/core.py'),
                                  'estadistica.core.calcular_rango_intercuartil': ( 'statistics.html#calcular_rango_intercuartil',
                                                                                    'estadistica/core.py'),
                                  'estadistica.core.graficar_caja_bigotes': ( 'statistics.html#graficar_caja_bigotes',
                                                                              'estadistica/core.py'),
                                  'estadistica.core.graficar_dispersion': ('statistics.html#graficar_dispersion', 'estadistica/core.py'),
                                  'estadistica.core.graficar_histograma': ('statistics.html#graficar_histograma', 'estadistica/core.py')}}}
