# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/statistics.ipynb.

# %% auto 0
__all__ = ['calcular_media', 'calcular_mediana', 'calcular_desviacion_estandar', 'calcular_rango_intercuartil',
           'graficar_histograma', 'graficar_caja_bigotes', 'graficar_dispersion']

# %% ../nbs/statistics.ipynb 2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# %% ../nbs/statistics.ipynb 3
def calcular_media(datos):
    return np.mean(datos)


def calcular_mediana(datos):
    return np.median(datos)


def calcular_desviacion_estandar(datos):
    return np.std(datos)


def calcular_rango_intercuartil(datos):
    return stats.iqr(datos)


def graficar_histograma(datos, titulo="Histograma", xlabel="Valor", ylabel="Frecuencia"):
    plt.figure(figsize=(10, 6))
    plt.hist(datos, bins=20, edgecolor='black')
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.show()


def graficar_caja_bigotes(datos, titulo="Caja y Bigotes", xlabel=""):
    plt.figure(figsize=(10, 6))
    sns.boxplot(datos)
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.show()

def graficar_dispersion(x, y, titulo="Diagrama de Dispersión", xlabel="X", ylabel="Y"):
    plt.figure(figsize=(10, 6))
    plt.scatter(x, y, edgecolor='black')
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.show()
